spring:
  profiles:
    active: pro
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    proxy-target-class: true
  cache:
    type: caffeine
  mail:
    host: smtp.163.com
    username: alwaysacc@163.com
    password: alwaysacc1
    default-encoding: utf-8
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 800
  servlet:
    multipart:
      max-file-size: 100MB
  data:
    solr:
      host: http://111.230.252.141:8983/solr/alwaysacc
server:
  error:
    whitelabel:
      enabled: false
  port: 8088
#  port: 8008

